### PR TITLE
made a quick fix to allow steam integration syncing to work again

### PR DESCRIPTION
**Pull request by jedKnighthook**
Using the fix proposed here: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/159

### CODE REVIEW

**Comment by jacket430** [comment]
Doesn't seem to work for me. Well, it lets me log in to sync the games once, but it breaks almost immediately and requires logging in again to fix it.

**Review by MGREMY — APPROVED** [review]

**Comment by Caraamon** [comment]
Worked for me!

**Review by ryanpcmcquen — APPROVED** [review]

**Comment by Peantab** [comment]
You can get similar results by commenting-out line https://github.com/FriendsOfGalaxy/galaxy-integration-steam/blob/master/src/steam_network/protocol_client.py#L232

It awaits for some message from Steam server with a login key, it never comes. If skipped, one can log-in correctly, but after application restart it probably tries to log-in with an empty key (one needs to Disconnect integration and Connect again in Galaxy settings). I guess it's necessary to have that key not to go through 2FA each time. I have no idea why that key stopped coming recently.

**Comment by Ariikitty** [comment]
It seems this fix isn't working fully. It allows the connect to succeed but like others before me have commented, it doesn't keep you connected if you restart the app. The other issue I have found is it doesn't seem to track achievement progress.
Here's what it shows in Galaxy 2.0 after syncing connections:
image
And my actual achievement progress from Steam:
image

**Comment by ABaumher** [comment]
The issue also isn't guarenteed to work as expected. The reason the Timeout occurs is because the function never gets called, let alone finishes. This is a Steam-side thing, nothing we can do there. In essence, this just ignores the call and pretends it returned ok. A problem arises when we still need to do Two-Factor Authentication, but since the return value is simply NoActionRequired, it will fail. More likely, it'll crash. The public backup exists to handle login issues that people far more clever than me have tried to fix and had a bunch of trouble with. I'm hesitant to simply ignore it. Also, it stores the login to the cache (somehow, not there yet), which is why you need to login each time. If nothing is written to any caches GOG has, that would affect achievements as well. I'd recommend closing this PR until a better fix is found.

**Comment by jedKnighthook** [comment]
Yeah that's fair. This PR was a little impulsive on my part as I was getting frustrated the steam integration wasn't working along with other weird issues I was having with GOG somehow crashing other parts of my PC. Hopefully steam fixes their API sometime soon so we can get this fixed properly.

**Comment by ABaumher** [comment]
If it's any consolation, i am working on a fix. Do have some help, and you are welcome to join in.
https://github.com/FriendsOfGalaxy/galaxy-integration-steam/discussions/164

**Pull request closed without merging**
